import { StoreContext } from "@/shared/arch/store_context";
import Head from "next/head";
import { useContext, useEffect } from "react";

const Home = () => {
  const { authStore } = useContext(StoreContext);
  useEffect(() => {
    authStore.login();
  }, [authStore]);
  return (
    <>
      <Head>
        <title>Tutor app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;
