import HomeBanner from "@/modules/home/components/home.banner.component";
import HomeExplore from "@/modules/home/components/home.explore.component";
import HomeKickStart from "@/modules/home/components/home.kick-start.component";
import HomeQuestions from "@/modules/home/components/home.questions.component";
import Footer from "@/shared/components/footer/footer.component";
import AppLayout from "@/shared/components/layouts/app-layout.component";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Tutor app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <HomeBanner />
        <HomeExplore />
        <HomeQuestions />
        <HomeKickStart />
        <Footer />
      </AppLayout>
    </>
  );
};

export default Home;
