import LoginButton from "@/modules/auth/components/login-button.component";
import LogOutButton from "@/modules/auth/components/logout-button.component";
import SignUpButton from "@/modules/auth/components/signup-button.component";
import { authStore } from "@/modules/auth/data/auth.store";
import Head from "next/head";
import { useSnapshot } from "valtio";

const Home = () => {
  const snapShot = useSnapshot(authStore);
  return (
    <>
      <Head>
        <title>Tutor app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginButton />
      <SignUpButton />
      <LogOutButton />
      <div>{snapShot.user?.username}</div>
      <div>{snapShot.user?.email}</div>
    </>
  );
};

export default Home;
